stages:
  - test_javascript
  - test_python
  - test_php

test_javascript:
  stage: test_javascript
  image: node:19.7.0-alpine3.17
  script:
    - echo "Running JavaScript tests"
  tags: 
    - docker

test_python:
  stage: test_python
  image: python:3.11.2-alpine3.17
  script:
    - echo "Running Python tests"
  tags: 
    - docker

test_php:
  stage: test_php
  image: php:8.2.3-cli-alpine3.17
  script:
    - echo "Running PHP tests"
  tags: 
    - docker