stages:
  - build
  - deploy

build-code-job:
  stage: build
  image: node:18-buster
  script:
    - npm install
  tags:
    - docker

deploy-code-job:
  stage: deploy
  image: node:18-buster
  variables:
    GITHUB_URL: git@github.com:Fatedcircle/express-hello-world.git
  before_script:
    - 'which ssh-agent || ( apt-get update -y && apt-get install openssh-client -y )'
    - eval `ssh-agent -s`
    - echo "$PRIVATE_SSH_KEY" > /tmp/private_key   # Sla de SSH-sleutel op in een tijdelijk bestand
    - chmod 600 /tmp/private_key                  # Stel de juiste machtigingen in op het bestand
    - ssh-add /tmp/private_key                    # Voeg de SSH-sleutel toe aan de SSH-agent
    - mkdir -p ~/.ssh
    - ssh-keyscan -t rsa gitlab.com >> ~/.ssh/known_hosts
    - ssh-keyscan -t rsa github.com >> ~/.ssh/known_hosts

  script: 
    - echo "Deploy test1"
  tags:
    - docker
  needs:
    - job: build-code-job